In [1]:
#q1-a
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)


Reversed array: [5 4 6 3 2 1]


In [2]:
#q1-b
array1 = np.array([[1, 2, 3], [2, 4, 5], [1, 2, 3]])

# Method 1: Using flatten()
flat1 = array1.flatten()

# Method 2: Using ravel()
flat2 = array1.ravel()

print("Flattened array (flatten):", flat1)
print("Flattened array (ravel):", flat2)


Flattened array (flatten): [1 2 3 2 4 5 1 2 3]
Flattened array (ravel): [1 2 3 2 4 5 1 2 3]


In [3]:
#q1-c
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[1, 2], [3, 4]])

# Method 1: Using array_equal
print("Arrays equal?", np.array_equal(arr1, arr2))

# Method 2: Using element-wise comparison
print("Element-wise comparison:\n", arr1 == arr2)


Arrays equal? True
Element-wise comparison:
 [[ True  True]
 [ True  True]]


In [4]:
#q1-d
# i.
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
val, count = np.unique(x, return_counts=True)
most_freq = val[np.argmax(count)]
indices = np.where(x == most_freq)
print("Most frequent in x:", most_freq)
print("Indices:", indices)

# ii.
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
val_y, count_y = np.unique(y, return_counts=True)
most_freq_y = val_y[np.argmax(count_y)]
indices_y = np.where(y == most_freq_y)
print("Most frequent in y:", most_freq_y)
print("Indices:", indices_y)


Most frequent in x: 1
Indices: (array([0, 5, 7, 8, 9]),)
Most frequent in y: 1
Indices: (array([0, 1, 2]),)


In [5]:
#q1-e
gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]')

# i. Sum of all elements
total_sum = gfg.sum()

# ii. Row-wise sum
row_sum = gfg.sum(axis=1)

# iii. Column-wise sum
col_sum = gfg.sum(axis=0)

print("Total sum:", total_sum)
print("Row-wise sum:", row_sum)
print("Column-wise sum:", col_sum)


Total sum: 45
Row-wise sum: [[14]
 [16]
 [15]]
Column-wise sum: [[20  9 16]]


In [6]:
#q1-f
n_array = np.array([[55, 25, 15], [30, 44, 2], [11, 45, 77]])

# i. Diagonal sum
diag_sum = np.trace(n_array)

# ii. Eigenvalues and iii. Eigenvectors
eigen_vals, eigen_vecs = np.linalg.eig(n_array)

# iv. Inverse
inverse = np.linalg.inv(n_array)

# v. Determinant
det = np.linalg.det(n_array)

print("Diagonal sum:", diag_sum)
print("Eigenvalues:", eigen_vals)
print("Eigenvectors:\n", eigen_vecs)
print("Inverse:\n", inverse)
print("Determinant:", det)


Diagonal sum: 176
Eigenvalues: [98.16835147 28.097044   49.73460452]
Eigenvectors:
 [[ 0.4574917   0.34637121 -0.15017693]
 [ 0.28447814 -0.72784061 -0.4852124 ]
 [ 0.84248058  0.59184038  0.8614034 ]]
Inverse:
 [[ 0.02404141 -0.00911212 -0.00444671]
 [-0.01667882  0.02966905  0.0024785 ]
 [ 0.00631287 -0.01603732  0.01217379]]
Determinant: 137180.0000000001


In [10]:
#q1-g
# i.
p1 = np.array([[1, 2], [2, 3]])
q1 = np.array([[4, 5], [6, 7]])
mult1 = np.dot(p1, q1)
cov1 = np.cov(p1.T, q1.T)

# ii.
p2 = np.array([[1, 2], [2, 3], [4, 5]])
q2 = np.array([[4, 5, 1], [6, 7, 2]])
mult2 = np.dot(p2, q2)
# cov2 = np.cov(p2.T, q2.T) # Removed due to incompatible shapes for covariance calculation

print("Multiplication 1:\n", mult1)
print("Covariance 1:\n", cov1)

print("Multiplication 2:\n", mult2)
# print("Covariance 2:\n", cov2) # Removed due to incompatible shapes for covariance calculation

Multiplication 1:
 [[16 19]
 [26 31]]
Covariance 1:
 [[0.5 0.5 1.  1. ]
 [0.5 0.5 1.  1. ]
 [1.  1.  2.  2. ]
 [1.  1.  2.  2. ]]
Multiplication 2:
 [[16 19  5]
 [26 31  8]
 [46 55 14]]


In [11]:
#q1-h
x = np.array([[2, 3, 4], [3, 2, 9]])
y = np.array([[1, 5, 0], [5, 10, 3]])

# Inner product
inner_prod = np.inner(x, y)

# Outer product (flattened first)
outer_prod = np.outer(x.flatten(), y.flatten())

# Cartesian product
cartesian_prod = np.array(np.meshgrid(x.flatten(), y.flatten())).T.reshape(-1, 2)

print("Inner Product:\n", inner_prod)
print("Outer Product:\n", outer_prod)
print("Cartesian Product:\n", cartesian_prod)


Inner Product:
 [[17 52]
 [13 62]]
Outer Product:
 [[ 2 10  0 10 20  6]
 [ 3 15  0 15 30  9]
 [ 4 20  0 20 40 12]
 [ 3 15  0 15 30  9]
 [ 2 10  0 10 20  6]
 [ 9 45  0 45 90 27]]
Cartesian Product:
 [[ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 4  1]
 [ 4  5]
 [ 4  0]
 [ 4  5]
 [ 4 10]
 [ 4  3]
 [ 3  1]
 [ 3  5]
 [ 3  0]
 [ 3  5]
 [ 3 10]
 [ 3  3]
 [ 2  1]
 [ 2  5]
 [ 2  0]
 [ 2  5]
 [ 2 10]
 [ 2  3]
 [ 9  1]
 [ 9  5]
 [ 9  0]
 [ 9  5]
 [ 9 10]
 [ 9  3]]


# Q2

In [12]:
import numpy as np

array = np.array([[1, -2, 3], [-4, 5, -6]])
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])


In [13]:
#q2-a-i
abs_array = np.abs(array)
print(abs_array)


[[1 2 3]
 [4 5 6]]


In [14]:
#Q2-a-ii
flat = array.flatten()
print("Flattened:", flat)
print("Percentiles:", np.percentile(flat, [25, 50, 75]))


Flattened: [ 1 -2  3 -4  5 -6]
Percentiles: [-3.5 -0.5  2.5]


In [15]:
print("Column-wise Percentiles:")
print("25th:", np.percentile(array, 25, axis=0))
print("50th:", np.percentile(array, 50, axis=0))
print("75th:", np.percentile(array, 75, axis=0))


Column-wise Percentiles:
25th: [-2.75 -0.25 -3.75]
50th: [-1.5  1.5 -1.5]
75th: [-0.25  3.25  0.75]


In [16]:
print("Row-wise Percentiles:")
print("25th:", np.percentile(array, 25, axis=1))
print("50th:", np.percentile(array, 50, axis=1))
print("75th:", np.percentile(array, 75, axis=1))


Row-wise Percentiles:
25th: [-0.5 -5. ]
50th: [ 1. -4.]
75th: [2.  0.5]


In [17]:
#Q-2-a-iii
print("Flattened Mean:", np.mean(flat))
print("Flattened Median:", np.median(flat))
print("Flattened Std Dev:", np.std(flat))


Flattened Mean: -0.5
Flattened Median: -0.5
Flattened Std Dev: 3.8622100754188224


In [18]:
print("Column-wise Mean:", np.mean(array, axis=0))
print("Column-wise Median:", np.median(array, axis=0))
print("Column-wise Std Dev:", np.std(array, axis=0))


Column-wise Mean: [-1.5  1.5 -1.5]
Column-wise Median: [-1.5  1.5 -1.5]
Column-wise Std Dev: [2.5 3.5 4.5]


In [19]:
print("Row-wise Mean:", np.mean(array, axis=1))
print("Row-wise Median:", np.median(array, axis=1))
print("Row-wise Std Dev:", np.std(array, axis=1))


Row-wise Mean: [ 0.66666667 -1.66666667]
Row-wise Median: [ 1. -4.]
Row-wise Std Dev: [2.05480467 4.78423336]


In [20]:
#Q-2-b
np.floor(a)


array([-2., -2., -1.,  0.,  1.,  1.,  3.])

In [21]:
np.ceil(a)


array([-1., -1., -0.,  1.,  2.,  2.,  3.])

In [22]:
np.trunc(a)


array([-1., -1., -0.,  0.,  1.,  1.,  3.])

In [23]:
np.round(a)


array([-2., -2., -0.,  0.,  2.,  2.,  3.])

# Q3

In [24]:
import numpy as np

array = np.array([10, 52, 62, 16, 16, 54, 453])


In [25]:
#Q3-a-i
sorted_array = np.sort(array)
print("Sorted array:", sorted_array)


Sorted array: [ 10  16  16  52  54  62 453]


In [26]:
#Q3-a-ii
sorted_indices = np.argsort(array)
print("Indices of sorted array:", sorted_indices)


Indices of sorted array: [0 3 4 1 5 2 6]


In [27]:
#Q3-a-iii
smallest_4 = np.sort(array)[:4]
print("4 Smallest elements:", smallest_4)


4 Smallest elements: [10 16 16 52]


In [28]:
#Q3-a-iv
largest_5 = np.sort(array)[-5:]
print("5 Largest elements:", largest_5)


5 Largest elements: [ 16  52  54  62 453]


In [29]:
#q3-b
array_b = np.array([1.0, 1.2, 2.2, 2.0, 3.0, 2.0])


In [30]:
#i
int_elements = array_b[array_b == array_b.astype(int)]
print("Integer elements:", int_elements)


Integer elements: [1. 2. 3. 2.]


In [31]:
#ii
float_elements = array_b[array_b != array_b.astype(int)]
print("Float elements:", float_elements)


Float elements: [1.2 2.2]
